### ISSUE TITLE
pip install requirements.txt failed with conda env python version 3.9.19

### ISSUE THREAD

**Issue by jessie831024** [alex-hh/eDICE#3]
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.11.0

**Comment by alex-hh** [comment]
hi: as a first attempt to resolve this issue you could perhaps try with a more recent tensorflow version (e.g. 2.13.0) - I haven't tested this but would be surprised if there are major differences.

it should also be possible to find a way to install tensorflow 2.11.0 but I'm not sure of the best way to do this.

let me know if you have further problems/questions

**Comment by jessie831024** [comment]
I managed to update the tensorflow version to 2.17.0 and resolved conflicts of other packages. 
[requirements_pip_freeze.txt](https://github.com/user-attachments/files/16412054/requirements_pip_freeze.txt)

**Comment by jessie831024** [comment]
However, there is a bug when running: 
`python scripts/train_roadmap.py --experiment_name "myRoadmapExperiment" --train_splits "train" --epochs 20 --transformation "arcsinh" --embed_dim 256 --lr 0.0003 --n_targets 120` 

(edice) jessie@192 eDICE % python scripts/train_roadmap.py --experiment_name "myRoadmapExperiment" --train_splits "train" --epochs 20 --transformation "arcsinh" --embed_dim 256 --lr 0.0003 --n_targets 120
Namespace(experiment_name='myRoadmapExperiment', dataset='RoadmapSample', data_dir='sample_data', experiment_group=None, split_file='sample_data/roadmap/predictd_splits.json', train_splits=['train'], test_run=False, seed=211, epochs=20, transformation='arcsinh', n_attn_heads=4, n_attn_layers=1, embed_dim=256, lr=0.0003, intermediate_fc_dim=128, transformer_dropout=0.1, embedding_dropout=0.0, intermediate_fc_dropout=0.0, n_targets=120, min_targets=None, max_targets=None, final_checkpoint=False, resume=False, agg_metrics_only=False, layer_norm_type=None, decoder_layers=2, decoder_hidden=2048, decoder_dropout=0.3, total_bins=None)
SETTING SEED 211
{'data_dir': 'sample_data', 'filepath': 'roadmap/SAMPLE_chr21_roadmap_train.h5', 'idmap': 'sample_data/roadmap/idmap.json', 'name': 'RoadmapSample', 'total_bins': None, 'splits': 'sample_data/roadmap/predictd_splits.json'}
Loading model
Loading model class CellAssayCrossFactoriser
Embed dim 256
Instantiated embedder interpreting signal as a graph of 127 nodes and 24 feats
Instantiated embedder interpreting signal as a graph of 24 nodes and 127 feats
Training from scratch (checkpoint None)
Getting callbacks
Traceback (most recent call last):
  File "/Users/jessie/github/eDICE/scripts/train_roadmap.py", line 151, in <module>
    main(args)
  File "/Users/jessie/github/eDICE/scripts/train_roadmap.py", line 124, in main
    callbacks, output_dir = get_callbacks(args, dataset, checkpoint=checkpoint)
  File "/opt/miniconda3/envs/edice/lib/python3.9/site-packages/eDICE-0.1-py3.9.egg/edice/utils/train_utils.py", line 52, in get_callbacks
    ModelCheckpoint(
  File "/opt/miniconda3/envs/edice/lib/python3.9/site-packages/keras/src/callbacks/model_checkpoint.py", line 183, in __init__
    raise ValueError(
ValueError: When using `save_weights_only=True` in `ModelCheckpoint`, the filepath provided must end in `.weights.h5` (Keras weights format). Received: filepath=outputs/myRoadmapExperiment/version_1/checkpoints/edice

**Comment by alex-hh** [comment]
looks like this may be due to upgrading to keras 3 . can you try downgrading to keras 2 by installing tensorflow<=2.15.0? https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility

**Comment by jessie831024** [comment]
I managed to get the training script working using the sample_data with some tweaks. 
Here is my setup: 
- Mac OS 14.5 M3 chip
- Python 3.11.0
- tensorflow==2.13.0
- keras==2.13.1

There were two error msgs I encountered and fixed so it runs - not sure if it's to do with different package versions. Do you want me do a PR so you can review it?

**Comment by alex-hh** [comment]
you're welcome to open a PR! im not clear yet whether the modifications are necessary to get things running but happy to take a look at what you did and have available as an example in case it's useful to anyone else trying to run the code.
